version: '3'
services:
  apache:
    container_name: apache-web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"